conky.config = {
    out_to_x = true,
    own_window = false,
    double_buffer = true,
    alignment = 'bottom_middle',
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    update_interval = 1,
    use_xft = true,
    xftfont = 'Cyber Horizon:size=32',        -- fallback for plain text
    override_utf8_locale = true,
};

conky.text = [[
${font Cyber Horizon:size=32:bold}${time %A}${font}
]];
