conky.config = {
    alignment = 'bottom_middle',
    background = true,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'aquamarine',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = false,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans Mono:size=12',
    gap_x = 60,
    gap_y = 60,
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = true,
    own_window_argb_visual = true,
    own_window_class = 'conky',
    own_window_type = 'override',
    own_window_transparent = true,
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
    xftalpha = 0.9
}  

conky.text = [[
${font Cyber Horizon:size=32:bold}${time %A}${font}
]];
